name = "NShapes"
uuid = "97e3950c-66f8-4045-a0e7-438c70f7ae40"
authors = ["Amr <amr@programmer.net>"]
repo = "https://github.com/cyber-amr/NShapes.jl.git"
version = "1.0.0-DEV"

[compat]
julia = "1"
Aqua = "0.8"
Test = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
